### ISSUE TITLE
assoc prepare segments task doesn't work on non-autosomes

### ISSUE THREAD

**Issue by aofarrel** [DataBiosphere/analysis_pipeline_WDL#65]
Traceback (most recent call last):
  File "assoc-aggregate/prepare_segments_1.py", line 62, in <module>
    input_gdss = pair_chromosome_gds(IIinput_gds_filesII)
  File "assoc-aggregate/prepare_segments_1.py", line 45, in pair_chromosome_gds
    gdss[int(find_chromosome(file_array[i]))] = os.path.basename(file_array[i])
ValueError: invalid literal for int() with base 10: 'X'

**Comment by aofarrel** [comment]
Verified fixed on Terra here: https://github.com/DataBiosphere/analysis_pipeline_WDL/pull/58/commits/63e0cf183f14eb91c2a8dffc882f376a9d64b0c7
