### ISSUE TITLE
Call cacheing does not regenerate segments OR including chrX requires all other chrs to be included

### ISSUE THREAD

**Issue by aofarrel** [DataBiosphere/analysis_pipeline_WDL#67]
On Terra, I ran assoc-aggregate with chr1-22+X. It passed all the way through.

To debug #66, I ran it again on Terra with just chr1, chr2, and chrX. The segments.txt file was call cached and includes all of the chromosomes. This results in it erroring... during an error message.
Code:
```
if max(output_segments) != len(output_segments): # I don't know if this case is actually problematic but I suspect it will be.
	print("ERROR: Subsequent code relies on output_segments being a list of consecutive integers.")
	print("Debug information: Max of list is %s, len of list is %s" % [max(output_segments), len(output_segments)])
	print("Debug information: List is as follows:\n\t%s" % output_segments)
	exit(1)
```

Output:

> ERROR: Subsequent code relies on output_segments being a list of consecutive integers.
> Traceback (most recent call last):
> File "<stdin>", line 92, in <module>
> TypeError: not enough arguments for format string

**Comment by aofarrel** [comment]
Original post:
On Terra, I ran assoc-aggregate with chr1-22+X. It passed all the way through.

To debug #66, I ran it again on Terra with just chr1, chr2, and chrX. The segments.txt file was call cached and includes all of the chromosomes. This results in it erroring... during an error message.
Code:
```
if max(output_segments) != len(output_segments): # I don't know if this case is actually problematic but I suspect it will be.
	print("ERROR: Subsequent code relies on output_segments being a list of consecutive integers.")
	print("Debug information: Max of list is %s, len of list is %s" % [max(output_segments), len(output_segments)])
	print("Debug information: List is as follows:\n\t%s" % output_segments)
	exit(1)
```

Output:

> ERROR: Subsequent code relies on output_segments being a list of consecutive integers.
> Traceback (most recent call last):
> File "<stdin>", line 92, in <module>
> TypeError: not enough arguments for format string
